name: Update README

on:
  schedule:
    - cron: '0 * * * *'    # Runs every hour
  workflow_dispatch:       # Manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python update_readme.py
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README" || echo "No changes"
          git push
